### PR TITLE
week 2

### PR DESCRIPTION
**Pull request by chlamydamanada**

### CODE REVIEW

**Comment by max-kriv0s** [comment]
run build production inctagram-gateway

**Comment by max-kriv0s** [comment]
run build production inctagram-gateway

**Comment by max-kriv0s** [comment]
run build production inctagram-gateway

**Comment by max-kriv0s** [comment]
run build production inctagram-gateway

**Comment by max-kriv0s** [comment]
run build production inctagram-gateway

**Comment by max-kriv0s** [comment]
run build production inctagram-gateway

**Comment by max-kriv0s** [comment]
run build production inctagram-gateway

**Comment by max-kriv0s** [comment]
run build production inctagram-upload-files

**Comment by max-kriv0s** [comment]
run build production inctagram-gateway

**Comment by max-kriv0s** [comment]
run build production inctagram-upload-files

**Comment by max-kriv0s** [comment]
run build production inctagram-gateway

**Comment by max-kriv0s** [comment]
run build production inctagram-gateway

**Comment by max-kriv0s** [comment]
run build production inctagram-upload-files

**Comment by max-kriv0s** [comment]
run build production inctagram-gateway

**Comment by max-kriv0s** [comment]
run build production inctagram-gateway

**Comment by max-kriv0s** [comment]
run build production inctagram-gateway

**Comment by max-kriv0s** [comment]
run build production inctagram-upload-files

**Comment by max-kriv0s** [comment]
run build production inctagram-gateway

**Comment by max-kriv0s** [comment]
run build production inctagram-gateway

**Comment by max-kriv0s** [comment]
run build production inctagram-gateway

**Comment by max-kriv0s** [comment]
run build production inctagram-gateway

**Comment by max-kriv0s** [comment]
run build production inctagram-gateway

**Comment by max-kriv0s** [comment]
run build production inctagram-upload-files

**Comment by max-kriv0s** [comment]
run build production inctagram-gateway

**Comment by max-kriv0s** [comment]
run build production inctagram-upload-files

**Comment by max-kriv0s** [comment]
run build production inctagram-gateway

**Comment by max-kriv0s** [comment]
run build production inctagram-upload-files

**Comment by max-kriv0s** [comment]
run build production inctagram-gateway

**Comment by max-kriv0s** [comment]
run build production inctagram-upload-files

**Comment by alexanderbalaban24** [comment]
run build production inctagram-gateway

**Comment by Nazim86** [comment]
run build production inctagram-gateway

**Pull request merged**
